
release:
	mkdir lnwordpress
	cp readme.txt gpl.txt local_names.php lnwordpress
	cp ln_demonstration.png lnwordpress/screenshot_1.png
	cp ln_demonstration.png ../website/output/
	tar cvzf ../website/output/lnwordpress.tgz lnwordpress

clean:
	rm -rf lnwordpress
	rm ../website/output/ln_demonstration.png
	rm ../website/output/lnwordpress.tgz

